name: blog deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm install vuepress  
    - run: npm run deploy
