name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
      publish_dir: ./dist