name: blog deploy

on:
  push:
    branches:
      - master

jobs:
  checkout-deploy:
    runs-on: ubuntu-latest

    steps:
       
      

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACCESS_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR:  dist
